baseURL: https://ewigl.github.io/
languageCode: zh-CN
defaultContentLanguage: zh-CN
defaultContentLanguageInSubdir: false
title: EwigLicht

hasCJKLanguage: true
enableEmoji: true

# Main Section Configuration (Optional)
# If not configured, Hugo will automatically select the section with the most pages
# This configuration affects functions such as recent articles on the homepage, search index, and archive pages
mainSections: ["posts"] # Multiple values can be configured, e.g. ["posts", "blog", "articles"]

permalinks:
  posts: /posts/:slug/
  projects: /projects/:slug/
  pages: /:slug/

pagination:
  pagerSize: 10
  path: "page"

taxonomies:
  category: categories
  # series: series
  tag: tags

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: true
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    style: github
    tabWidth: 2

outputs:
  home: ["HTML", "JSON", "WebAppManifest"]

outputFormats:
  WebAppManifest:
    mediaType: "application/manifest+json"
    baseName: "site"
    isPlainText: true

module:
  hugoVersion:
    extended: true
    min: 0.146.0
  imports:
    - path: github.com/tom2almighty/hugo-narrow

# For github pages image caching
caches:
  images:
    dir: :cacheDir/images
