main:
  - identifier: nav.projects
    name: Projects
    pageRef: /projects
    weight: 10
    params:
      icon: projects
  - identifier: nav.posts
    name: Posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - identifier: nav.tags
    name: Tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  # - identifier: nav.archives
  #   name: Archives
  #   pageRef: /archives
  #   weight: 50
  #   params:
  #     icon: archive

# footer menu
footer:
  - name: 待办
    pageRef: /to-do
    weight: 10
    params:
      icon: book-open
  - name: 应用
    pageRef: /apps
    weight: 20
    params:
      icon: apps
  - name: 关于
    pageRef: /about
    weight: 999
    params:
      icon: about

# footer social link
# social:
#   - name: GitHub
#     url: https://github.com/ewigl
#     weight: 10
#     params:
#       icon: github
